package com.hitrust.dsm.po;
// Generated 2017/8/10 �U�� 10:46:06 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DrinkMenuId generated by hbm2java
 */
@Embeddable
public class DrinkMenuId implements java.io.Serializable {

	private String dsId;
	private String dmName;

	public DrinkMenuId() {
	}

	public DrinkMenuId(String dsId, String dmName) {
		this.dsId = dsId;
		this.dmName = dmName;
	}

	@Column(name = "DS_ID", nullable = false, length = 4)
	public String getDsId() {
		return this.dsId;
	}

	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	@Column(name = "DM_NAME", nullable = false, length = 20)
	public String getDmName() {
		return this.dmName;
	}

	public void setDmName(String dmName) {
		this.dmName = dmName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DrinkMenuId))
			return false;
		DrinkMenuId castOther = (DrinkMenuId) other;

		return ((this.getDsId() == castOther.getDsId()) || (this.getDsId() != null && castOther.getDsId() != null
				&& this.getDsId().equals(castOther.getDsId())))
				&& ((this.getDmName() == castOther.getDmName()) || (this.getDmName() != null
						&& castOther.getDmName() != null && this.getDmName().equals(castOther.getDmName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDsId() == null ? 0 : this.getDsId().hashCode());
		result = 37 * result + (getDmName() == null ? 0 : this.getDmName().hashCode());
		return result;
	}

}
