package com.hitrust.dsm.po;
// Generated 2017/8/10 �U�� 10:46:06 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DrinkStore generated by hbm2java
 */
@Entity
@Table(name = "drink_store", catalog = "DSM")
public class DrinkStore implements java.io.Serializable {

	private String dsId;
	private String dsName;
	private String dsPhoto;
	private String dsAddr;

	public DrinkStore() {
	}

	public DrinkStore(String dsId, String dsName, String dsPhoto, String dsAddr) {
		this.dsId = dsId;
		this.dsName = dsName;
		this.dsPhoto = dsPhoto;
		this.dsAddr = dsAddr;
	}

	@Id

	@Column(name = "DS_ID", unique = true, nullable = false, length = 4)
	public String getDsId() {
		return this.dsId;
	}

	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	@Column(name = "DS_NAME", nullable = false, length = 30)
	public String getDsName() {
		return this.dsName;
	}

	public void setDsName(String dsName) {
		this.dsName = dsName;
	}

	@Column(name = "DS_PHOTO", nullable = false, length = 12)
	public String getDsPhoto() {
		return this.dsPhoto;
	}

	public void setDsPhoto(String dsPhoto) {
		this.dsPhoto = dsPhoto;
	}

	@Column(name = "DS_ADDR", nullable = false, length = 50)
	public String getDsAddr() {
		return this.dsAddr;
	}

	public void setDsAddr(String dsAddr) {
		this.dsAddr = dsAddr;
	}

}
