package com.hitrust.dsm.po;
// Generated 2017/8/10 �U�� 10:46:06 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DrinkMenu generated by hbm2java
 */
@Entity
@Table(name = "drink_menu", catalog = "DSM")
public class DrinkMenu implements java.io.Serializable {

	private DrinkMenuId id;
	private String dmPic;

	public DrinkMenu() {
	}

	public DrinkMenu(DrinkMenuId id, String dmPic) {
		this.id = id;
		this.dmPic = dmPic;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dsId", column = @Column(name = "DS_ID", nullable = false, length = 4)),
			@AttributeOverride(name = "dmName", column = @Column(name = "DM_NAME", nullable = false, length = 20)) })
	public DrinkMenuId getId() {
		return this.id;
	}

	public void setId(DrinkMenuId id) {
		this.id = id;
	}

	@Column(name = "DM_PIC", nullable = false, length = 4)
	public String getDmPic() {
		return this.dmPic;
	}

	public void setDmPic(String dmPic) {
		this.dmPic = dmPic;
	}

}
