package com.hitrust.dsm.po;
// Generated 2017/8/10 �U�� 10:46:06 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrderStore generated by hbm2java
 */
@Entity
@Table(name = "order_store", catalog = "DSM")
public class OrderStore implements java.io.Serializable {

	private String osId;
	private String osName;
	private String osPhoto;
	private String osAddr;

	public OrderStore() {
	}

	public OrderStore(String osId, String osName, String osPhoto, String osAddr) {
		this.osId = osId;
		this.osName = osName;
		this.osPhoto = osPhoto;
		this.osAddr = osAddr;
	}

	@Id

	@Column(name = "OS_ID", unique = true, nullable = false, length = 4)
	public String getOsId() {
		return this.osId;
	}

	public void setOsId(String osId) {
		this.osId = osId;
	}

	@Column(name = "OS_NAME", nullable = false, length = 30)
	public String getOsName() {
		return this.osName;
	}

	public void setOsName(String osName) {
		this.osName = osName;
	}

	@Column(name = "OS_PHOTO", nullable = false, length = 12)
	public String getOsPhoto() {
		return this.osPhoto;
	}

	public void setOsPhoto(String osPhoto) {
		this.osPhoto = osPhoto;
	}

	@Column(name = "OS_ADDR", nullable = false, length = 50)
	public String getOsAddr() {
		return this.osAddr;
	}

	public void setOsAddr(String osAddr) {
		this.osAddr = osAddr;
	}

}
